### ISSUE TITLE
License says copyright Microsoft at the top of MIT license

### ISSUE THREAD

**Issue by abchatra** [Freenove/Makecode-Extension-Rover#1]
Copyright (c) Microsoft Corporation

This should say Copyright (c) <your company> as this is not from Microsoft

**Comment by SuhaylZhao** [comment]
> Copyright (c) Microsoft Corporation
> 
> This should say Copyright (c) as this is not from Microsoft

Hi，

Thank you for your work. I've changed it. Please check it.

Thanks again.
