### ISSUE TITLE
Add blocks information to Readme

### ISSUE THREAD

**Issue by abchatra** [Freenove/Makecode-Extension-Rover#2]
Readme is shown as help in the blocks. Please add block snapshot in the Readme so help teachers
and students 
https://makecode.com/pkg/Freenove/Makecode-Extension-Rover

**Comment by SuhaylZhao** [comment]
> Readme is shown as help in the blocks. Please add block snapshot in the Readme so help teachers
> and students
> https://makecode.com/pkg/Freenove/Makecode-Extension-Rover

Hi,

I've added more information about blocks. And added some examples.

Please check it. 

Thanks.
