### ISSUE TITLE
Don't use different colors in namespace

### ISSUE THREAD

**Issue by pelikhan** [Freenove/Makecode-Extension-Rover#3]
Avoid using different colors per group. Typically, the blocks have the same color of the category.

![image](https://user-images.githubusercontent.com/4175913/57464698-0176b980-7232-11e9-9b50-be48ad085c55.png)

**Comment by SuhaylZhao** [comment]
Hi,

Thanks for your work. I've changed the color of all the blocks to the same color. Please check it.

![blocks-colors](https://user-images.githubusercontent.com/3676296/57509557-18eb9a80-7337-11e9-95e2-9862bdd679b4.jpg)
